In [3]:
import pandas as pd

## Define path to table files

In [33]:
w_restaurant_PATH = 'D:\\w_restaurant.csv'
search_click_PATH = 'D:\\search_click.csv'

## load files into memory

In [34]:
w_restaurant_df = pd.read_csv(w_restaurant_PATH)
search_click_df = pd.read_csv(search_click_PATH)

In [35]:
w_restaurant_df

id                                  name  domain_id  closed  \
0            2                      นครินทร์ทันตกรรม          2       0   
1            4                          Corner House          1       0   
2            5                        วัดโลกยสุธาราม          4       0   
3            6                        นันท์คาราโอเกะ          1       0   
4            7                           Buono Caffe          1       0   
5           14                           บ้านมุมสบาย          1       0   
6           15                   Hing Fat Resteurant          1       0   
7           16                              Sazanami          1       0   
8           20                          ครัวทิพวัลย์          1       0   
9           21                          นกน้ำเต้าหู้          1       0   
10          24                        Rotee Me Chabu          1       0   
11          27                       แพอาหารธาราบุรี          1       0   
12          28                               Milkcow          1       0   
13          29            Jeep Came อาหารป่า & ดนตรี          1       0   
14          30                       The Coffee Shop          1       0   
15          32           The Rabbit หมูกระทะนานาชาติ          1       0   
16          34                               Mott 32          1       0   
17          35   ก๋วยเตี๋ยวเย็นตาโฟเจ๊หมวย นครสวรรค์          1       0   
18          36                        ร้านผักบุ้งบิน          1       0   
19          37                                 ลาวชง          1       0   
20          38                     บะหมี่ ลูกชิ้นปลา          1       0   
21          41                         ธัญรส สาขา 27          1       0   
22          42                     ข้าวขาหมู ป้าเพ็ญ          1       0   
23          44                      OMG OH MY GELATO          1       0   
24          45                        ลุงตุ๊เจ้าเก่า          1       0   
25          46                            Music Cofe          1       0   
26          49                             ขส. สเต็ก          1       0   
27          50      ร้านป้าเล็ก ก๋วยจั๊บ คลองบางหลวง          1       0   
28          51       โรงแรมมนต์ระวีพาวิเลี่ยนรีสอร์ท          1       0   
29          52                       A Day in Summer          1       0   
...        ...                                   ...        ...     ...   
246817  340007                          Ruj's Coffee          1       0   
246818  340011                               Coffman          1       0   
246819  340015                           ลากูนเทอเรซ          1       0   
246820  340022                              Riliro's          1       0   
246821  340024                          ผู้ชายขายหอย          1       0   
246822  340025                            Chang Xing          1       0   
246823  340027                          Takumi-chaya          1       0   
246824  340028              โรงแรมทาวน์อินทาวน์พัทยา          1       0   
246825  340029                           โค้งลาบเป็ด          1       0   
246826  340031                             ลาบเขยยอง          1       0   
246827  340035                       สำราญโภชนา อตก.          1       0   
246828  340036                               แพอลิสา          1       0   
246829  340037                   Fatboy's Burger Bar          1       0   
246830  340038       ดิ อิมพีเรียล หัวหิน บีชรีสอร์ท          3       0   
246831  340041                            ครัวศาลายา          1       0   
246832  340042                             โชคดีกาแฟ          1       0   
246833  340043                           เบอร์นีบาร์          1       0   
246834  340048                             Kuppadeli          1       1   
246835  340051                        ร้านครัวแกงป่า          1       0   
246836  340054                                คนึงหา          1       0   
246837  340056                         บึงกาฬลาบก้อย          1       0   
246838  340059                       

In [36]:
search_click_df.head()

click_timestamp                             search_id  business_id  \
0         11:38.9  5c004472-5ecc-4159-9698-9f329b8e26e1     298839.0   
1         30:51.3  5f34eca0-c04e-4c10-b600-54aa447dbd8e     171372.0   
2         32:09.6  8dc6d1f0-11f1-4239-9dd2-5c1674c81224      16157.0   
3         00:59.8  1a5810e9-3d1f-44b9-9a2e-26ede21c524b      89741.0   
4         23:36.8  6bc75e0d-fc65-471e-9926-ff6be6708639     189564.0   

   display_position  time_diff_nanos   ads  
0                 0     2.222400e+15  True  
1                 0     4.608380e+14  True  
2                 0     2.581490e+15  True  
3                 1     1.404580e+15  True  
4                 1     9.333590e+14  True

In [37]:
search_click_df.tail()

click_timestamp                             search_id  business_id  \
1048570         05:28.8  99aab616-6fc5-4fbf-994b-4aebee7bb360     278479.0   
1048571         15:28.8  d70a2c5d-ee94-4e4c-9f7c-c5faac6db12a     321885.0   
1048572         11:49.4  4c1de7fe-300e-41aa-9d01-914344fc3753     221035.0   
1048573         10:33.7  2ec0ddec-e450-4b98-9779-42b77aa7eda5     220572.0   
1048574         13:51.4  5741d9cf-b9f1-441d-aa83-d2b0179bf874     310448.0   

         display_position  time_diff_nanos    ads  
1048570                 8     2.072630e+11  False  
1048571                 8     6.931413e+10  False  
1048572                 8     3.105162e+10  False  
1048573                 8     7.848904e+10  False  
1048574                 8     3.157757e+10  False

In [38]:
search_click_df.shape

(1048575, 6)

# data preprocessing

## missing

In [12]:
search_click_df.isnull()

click_timestamp  search_id  business_id  display_position  \
0                  False      False        False             False   
1                  False      False        False             False   
2                  False      False        False             False   
3                  False      False        False             False   
4                  False      False        False             False   
5                  False      False        False             False   
6                  False      False        False             False   
7                  False      False        False             False   
8                  False      False        False             False   
9                  False      False        False             False   
10                 False      False        False             False   
11                 False      False        False             False   
12                 False      False        False             False   
13                 False      False        False             False   
14                 False      False        False             False   
15                 False      False        False             False   
16                 False      False        False             False   
17                 False      False        False             False   
18                 False      False        False             False   
19                 False      False        False             False   
20                 False      False        False             False   
21                 False      False        False             False   
22                 False      False        False             False   
23                 False      False        False             False   
24                 False      False        False             False   
25                 False      False        False             False   
26                 False      False        False             False   
27                 False      False        False             False   
28                 False      False        False             False   
29                 False      False        False             False   
...                  ...        ...          ...               ...   
1048545            False      False        False             False   
1048546            False      False        False             False   
1048547            False      False        False             False   
1048548            False      False        False             False   
1048549            False      False        False             False   
1048550            False      False        False             False   
1048551            False      False        False             False   
1048552            False      False        False             False   
1048553            False      False        False             False   
1048554            False      False        False             False   
1048555            False      False        False             False   
1048556            False      False        False             False   
1048557            False      False        False             False   
1048558            False      False        False             False   
1048559            False      False        False             False   
1048560            False      False        False             False   
1048561            False      False        False             False   
1048562            False      False        False             False   
1048563            False      False        False             False   
1048564            False      False        False             False   
1048565            False      False        False             False   
1048566            False      False        False             False   
1048567            False      False        False             False   
1048568            False      False        False             False   
1048569            False      False        False             False   
1048570            

In [13]:
search_click_df.isnull().any()

click_timestamp     False
search_id            True
business_id          True
display_position    False
time_diff_nanos     False
ads                 False
dtype: bool

In [39]:
w_restaurant_df.isnull().any()

id                         False
name                       False
domain_id                  False
closed                     False
city_name                  False
zipcode                     True
geohash                    False
new_open                   False
weighted_average_rating    False
number_of_chains            True
number_of_bookmarks         True
number_of_reviews          False
number_of_product_tags     False
total_number_of_views      False
number_of_checkins         False
number_of_menu_groups      False
number_of_menu_photos      False
category_name              False
price_range                 True
avg_price                   True
parking                     True
credit_card_accepted        True
good_for_groups             True
good_for_kids               True
bookable                    True
best_of_wongnai             True
wifi                        True
number_of_seats             True
music_venue                 True
hotel_restaurant            True
pet_friend

## delete row with missing value

In [40]:
w_restaurant_df.dropna(subset = ['zipcode','number_of_chains'])

id                                name  domain_id  closed  \
61         114                            มานีมีนม          1       0   
114        224                        สเต็กลุงหนวด          1       0   
115        225                            Mr.shake          1       0   
131        267                                 KFC          1       0   
140        297                          Miss Mamon          1       1   
149        344                     Inthanin Coffee          1       0   
194        429                     The Skin Clinic          2       0   
235        486                                 S&P          1       0   
243        501                         Holy Shrimp          1       0   
268        544                      Dunkin' Donuts          1       0   
316        613        take care beauty salon & spa          2       0   
325        623                               ดอยคำ          1       0   
382        693                       Panlee Bakery          1       0   
394        717                             Hongmin          1       0   
411        739                      MK Restaurants          1       0   
437        781                       Auntie Anne's          1       0   
448        800                      Hot Pot Buffet          1       0   
481        845                         Dairy Queen          1       0   
556        934                    Khongkwan Clinic          2       0   
591        983                     Santa Fe' Steak          1       0   
594        990                     S&P BAKERY SHOP          1       0   
608       1006                ภัตตาคารเชียงการีล่า          1       0   
609       1007  Bake a wish japanese homemade cake          1       0   
615       1015                        สเต็กลุงหนวด          1       0   
624       1027                              Ochaya          1       0   
637       1052                      Doctor Younger          2       0   
653       1076                   ภัตตาคารต้าเหลียน          1       0   
678       1109                     Chester's Grill          1       0   
691       1129                      Victory Bakery          1       0   
694       1135                          McDonald's          1       0   
...        ...                                 ...        ...     ...   
246311  339285                             ชาพะยอม          1       0   
246312  339286   สเวนเซ่นส์ เซ็นทรัลพลาซ่า ขอนแก่น          1       0   
246333  339308                       Texas Chicken          1       0   
246365  339343                         Dairy Queen          1       0   
246386  339368                                Amor          1       0   
246407  339390                          BB Clinic           2       0   
246425  339410                               ตำแหล          1       0   
246454  339445                           Pizza Hut          1       0   
246458  339449                         Farm Design          1       0   
246460  339451                   นายหัว โรตี-ชาชัก          1       1   
246466  339458                  พฤกษาคลินิกเวชกรรม          2       0   
246477  339469                   Kyo Cafe and Meal          1       0   
246490  339486                        Joom Zap Hut          1       0   
246508  339506            ZEN Japanese Restaurant           1       0   
246528  339528        BareHare Eyebrow & Wax Salon          2       0   
246533  339533                  ชายสี่บะหมี่เกี๊ยว          1       0   
246550  339552                                 S&P          1       0   
246561  339565                        Joom Zap Hut          1       0   
246586  339593                       กาแฟสดเด่นชัย          1       0   
246614  339635                             อีซี่ส์          1       0   
246619  339640                         บ้านไร่กาแฟ          1       0   
246620  339641                     Southern Coffee          1       0   
246646  339670     Four Seasons Chinese Restaurant          1       0 

In [41]:
w_restaurant_df = w_restaurant_df.dropna(subset = ['zipcode','number_of_chains'])

## fill default value to the data 

In [43]:
w_restaurant_df['parking'].fillna(0)

61        3.0
114       3.0
115       0.0
131       3.0
140       3.0
149       3.0
194       3.0
235       3.0
243       3.0
268       3.0
316       3.0
325       0.0
382       1.0
394       3.0
411       3.0
437       3.0
448       3.0
481       0.0
556       0.0
591       3.0
594       3.0
608       3.0
609       3.0
615       0.0
624       3.0
637       0.0
653       0.0
678       0.0
691       0.0
694       3.0
         ... 
246311    0.0
246312    0.0
246333    3.0
246365    0.0
246386    3.0
246407    3.0
246425    3.0
246454    3.0
246458    3.0
246460    3.0
246466    3.0
246477    3.0
246490    3.0
246508    3.0
246528    3.0
246533    1.0
246550    0.0
246561    3.0
246586    0.0
246614    0.0
246619    0.0
246620    3.0
246646    3.0
246680    0.0
246684    3.0
246722    1.0
246752    3.0
246815    3.0
246834    0.0
246842    3.0
Name: parking, Length: 13669, dtype: float64

In [44]:
w_restaurant_df['parking'] = w_restaurant_df['parking'].fillna(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


# select part of the table by value

## part of table = table[data_condition == True]

In [45]:
w_restaurant_df['parking'] > 5

61        False
114       False
115       False
131       False
140       False
149       False
194       False
235       False
243       False
268       False
316       False
325       False
382       False
394       False
411       False
437       False
448       False
481       False
556       False
591       False
594       False
608       False
609       False
615       False
624       False
637       False
653       False
678       False
691       False
694       False
          ...  
246311    False
246312    False
246333    False
246365    False
246386    False
246407    False
246425    False
246454    False
246458    False
246460    False
246466    False
246477    False
246490    False
246508    False
246528    False
246533    False
246550    False
246561    False
246586    False
246614    False
246619    False
246620    False
246646    False
246680    False
246684    False
246722    False
246752    False
246815    False
246834    False
246842    False
Name: parking, Length: 1

In [46]:
w_restaurant_df[w_restaurant_df['parking'] >= 3]

id                                name  domain_id  closed  \
61         114                            มานีมีนม          1       0   
114        224                        สเต็กลุงหนวด          1       0   
131        267                                 KFC          1       0   
140        297                          Miss Mamon          1       1   
149        344                     Inthanin Coffee          1       0   
194        429                     The Skin Clinic          2       0   
235        486                                 S&P          1       0   
243        501                         Holy Shrimp          1       0   
268        544                      Dunkin' Donuts          1       0   
316        613        take care beauty salon & spa          2       0   
394        717                             Hongmin          1       0   
411        739                      MK Restaurants          1       0   
437        781                       Auntie Anne's          1       0   
448        800                      Hot Pot Buffet          1       0   
591        983                     Santa Fe' Steak          1       0   
594        990                     S&P BAKERY SHOP          1       0   
608       1006                ภัตตาคารเชียงการีล่า          1       0   
609       1007  Bake a wish japanese homemade cake          1       0   
624       1027                              Ochaya          1       0   
694       1135                          McDonald's          1       0   
730       1195                    The Coffee Club           1       0   
769       1260                         Cafe Amazon          1       0   
808       1308                        Mister Donut          1       0   
822       1335                           Swensen's          1       0   
969       1535                                 KFC          1       0   
979       1549            Fuji Japanese Restaurant          1       0   
1006      1588                ก๋วยเตี๋ยวกั้งบ้านเพ          1       0   
1037      1642                        Mister Donut          1       0   
1088      1725                     Coconut Terrace          1       0   
1131      1824                        Black Canyon          1       0   
...        ...                                 ...        ...     ...   
246071  339028                         Burger King          1       0   
246075  339032                           Swensen's          1       0   
246106  339065                      MK Restaurants          1       0   
246136  339097                      Hachiban Ramen          1       0   
246138  339099                        สามเสนวิลล่า          1       0   
246182  339148            LAU SHAN DONG RESTAURANT          1       0   
246189  339156                            Yum Saap          1       0   
246196  339163                      Hachiban Ramen          1       0   
246255  339225            Fuji Japanese Restaurant          1       0   
246269  339241                             Koi Thé          1       0   
246274  339247                     Chester's Grill          1       0   
246333  339308                       Texas Chicken          1       0   
246386  339368                                Amor          1       0   
246407  339390                          BB Clinic           2       0   
246425  339410                               ตำแหล          1       0   
246454  339445                           Pizza Hut          1       0   
246458  339449                         Farm Design          1       0   
246460  339451                   นายหัว โรตี-ชาชัก          1       1   
246466  339458                  พฤกษาคลินิกเวชกรรม          2       0   
246477  339469                   Kyo Cafe and Meal          1       0   
246490  339486                        Joom Zap Hut          1       0   
246508  339506            ZEN Japanese Restaurant           1       0   
246528  339528        BareHare Eyebrow & Wax Salon          2       0 

# HW select all resturants from your hometown

In [47]:
w_restaurant_df = pd.read_csv(w_resterant_PATH)

In [48]:
w_restaurant_df['city_name'] = 'Khon Kaen'

In [49]:
w_restaurant_df[w_restaurant_df['city_name']=='Khon Kaen']

id                                  name  domain_id  closed  \
0            2                      นครินทร์ทันตกรรม          2       0   
1            4                          Corner House          1       0   
2            5                        วัดโลกยสุธาราม          4       0   
3            6                        นันท์คาราโอเกะ          1       0   
4            7                           Buono Caffe          1       0   
5           14                           บ้านมุมสบาย          1       0   
6           15                   Hing Fat Resteurant          1       0   
7           16                              Sazanami          1       0   
8           20                          ครัวทิพวัลย์          1       0   
9           21                          นกน้ำเต้าหู้          1       0   
10          24                        Rotee Me Chabu          1       0   
11          27                       แพอาหารธาราบุรี          1       0   
12          28                               Milkcow          1       0   
13          29            Jeep Came อาหารป่า & ดนตรี          1       0   
14          30                       The Coffee Shop          1       0   
15          32           The Rabbit หมูกระทะนานาชาติ          1       0   
16          34                               Mott 32          1       0   
17          35   ก๋วยเตี๋ยวเย็นตาโฟเจ๊หมวย นครสวรรค์          1       0   
18          36                        ร้านผักบุ้งบิน          1       0   
19          37                                 ลาวชง          1       0   
20          38                     บะหมี่ ลูกชิ้นปลา          1       0   
21          41                         ธัญรส สาขา 27          1       0   
22          42                     ข้าวขาหมู ป้าเพ็ญ          1       0   
23          44                      OMG OH MY GELATO          1       0   
24          45                        ลุงตุ๊เจ้าเก่า          1       0   
25          46                            Music Cofe          1       0   
26          49                             ขส. สเต็ก          1       0   
27          50      ร้านป้าเล็ก ก๋วยจั๊บ คลองบางหลวง          1       0   
28          51       โรงแรมมนต์ระวีพาวิเลี่ยนรีสอร์ท          1       0   
29          52                       A Day in Summer          1       0   
...        ...                                   ...        ...     ...   
246817  340007                          Ruj's Coffee          1       0   
246818  340011                               Coffman          1       0   
246819  340015                           ลากูนเทอเรซ          1       0   
246820  340022                              Riliro's          1       0   
246821  340024                          ผู้ชายขายหอย          1       0   
246822  340025                            Chang Xing          1       0   
246823  340027                          Takumi-chaya          1       0   
246824  340028              โรงแรมทาวน์อินทาวน์พัทยา          1       0   
246825  340029                           โค้งลาบเป็ด          1       0   
246826  340031                             ลาบเขยยอง          1       0   
246827  340035                       สำราญโภชนา อตก.          1       0   
246828  340036                               แพอลิสา          1       0   
246829  340037                   Fatboy's Burger Bar          1       0   
246830  340038       ดิ อิมพีเรียล หัวหิน บีชรีสอร์ท          3       0   
246831  340041                            ครัวศาลายา          1       0   
246832  340042                             โชคดีกาแฟ          1       0   
246833  340043                           เบอร์นีบาร์          1       0   
246834  340048                             Kuppadeli          1       1   
246835  340051                        ร้านครัวแกงป่า          1       0   
246836  340054                                คนึงหา          1       0   
246837  340056                         บึงกาฬลาบก้อย          1       0   
246838  340059                       

## save table to a file

In [50]:
w_restaurant_df.to_csv('test.csv')

## WEEK2

In [1]:
import pandas as pd

#### ที่ import ใหม่เพราะจะได้ไม่ต้องรันใหม่ตั้งแต่แรก

In [2]:
w_restaurant_PATH = 'D:\\w_restaurant.csv'
search_click_PATH = 'D:\\search_click.csv'
w_restaurant_df = pd.read_csv(w_restaurant_PATH)
search_click_df = pd.read_csv(search_click_PATH)

### เรียกดูในส่วนหัวตาราง

In [3]:
w_restaurant_df.head()

id              name  domain_id  closed                    city_name  \
0   2  นครินทร์ทันตกรรม          2       0              Samut Songkhram   
1   4      Corner House          1       0  Bangkok Metropolitan Region   
2   5    วัดโลกยสุธาราม          4       0     Phra Nakhon Si Ayutthaya   
3   6    นันท์คาราโอเกะ          1       0  Bangkok Metropolitan Region   
4   7       Buono Caffe          1       0  Bangkok Metropolitan Region   

  zipcode  geohash  new_open  weighted_average_rating  number_of_chains  ...  \
0   75000  w4rh7g3         0                 5.000000               NaN  ...   
1   12150  w4rx73h         0                 2.000000               NaN  ...   
2   13000  w4x98jk         0                 4.000000               NaN  ...   
3   10700  w4rqw9q         0                 0.000000               NaN  ...   
4   10220  w4rx4gd         0                 3.738462               NaN  ...   

   good_for_groups  good_for_kids  bookable  best_of_wongnai  wifi  \
0              NaN            NaN       NaN              NaN   NaN   
1              NaN            NaN       NaN              NaN   NaN   
2              NaN            NaN       NaN              NaN   NaN   
3              NaN            NaN       NaN              NaN   NaN   
4              NaN            NaN       NaN              NaN   1.0   

   number_of_seats  music_venue hotel_restaurant  pet_friendly  delivery  
0             13.0          NaN              NaN           NaN       NaN  
1              NaN          NaN              NaN           NaN       NaN  
2              NaN          NaN              NaN           NaN       NaN  
3              NaN          NaN              NaN           NaN       NaN  
4              2.0          NaN              NaN           NaN       NaN  

[5 rows x 32 columns]

## select only some columns
เลือกเฉพาะคอลัมที่เราต้องการ

สร้างชื่อตารางใหม่เพื่อเก็บตารางใหม่ที่เราเลือกเฉพาะคอลัมน์ที่ต้องการ

In [56]:
small_table = w_restaurant_df[['name','city_name','zipcode','weighted_average_rating']]
small_table

name                    city_name  \
0                           นครินทร์ทันตกรรม              Samut Songkhram   
1                               Corner House  Bangkok Metropolitan Region   
2                             วัดโลกยสุธาราม     Phra Nakhon Si Ayutthaya   
3                             นันท์คาราโอเกะ  Bangkok Metropolitan Region   
4                                Buono Caffe  Bangkok Metropolitan Region   
5                                บ้านมุมสบาย                    Chon Buri   
6                        Hing Fat Resteurant              New Territories   
7                                   Sazanami  Bangkok Metropolitan Region   
8                               ครัวทิพวัลย์                        Krabi   
9                               นกน้ำเต้าหู้                   Narathiwat   
10                            Rotee Me Chabu  Bangkok Metropolitan Region   
11                           แพอาหารธาราบุรี                 Kanchanaburi   
12                                   Milkcow                    Singapore   
13                Jeep Came อาหารป่า & ดนตรี  Bangkok Metropolitan Region   
14                           The Coffee Shop                      เขาใหญ่   
15               The Rabbit หมูกระทะนานาชาติ                    Chon Buri   
16                                   Mott 32              New Territories   
17       ก๋วยเตี๋ยวเย็นตาโฟเจ๊หมวย นครสวรรค์                 Nakhon Sawan   
18                            ร้านผักบุ้งบิน                  Phitsanulok   
19                                     ลาวชง  Bangkok Metropolitan Region   
20                         บะหมี่ ลูกชิ้นปลา  Bangkok Metropolitan Region   
21                             ธัญรส สาขา 27                  Phitsanulok   
22                         ข้าวขาหมู ป้าเพ็ญ  Bangkok Metropolitan Region   
23                          OMG OH MY GELATO  Bangkok Metropolitan Region   
24                            ลุงตุ๊เจ้าเก่า     Phra Nakhon Si Ayutthaya   
25                                Music Cofe                   Chiang Rai   
26                                 ขส. สเต็ก  Bangkok Metropolitan Region   
27          ร้านป้าเล็ก ก๋วยจั๊บ คลองบางหลวง  Bangkok Metropolitan Region   
28           โรงแรมมนต์ระวีพาวิเลี่ยนรีสอร์ท                  Phitsanulok   
29                           A Day in Summer  Bangkok Metropolitan Region   
...                                      ...                          ...   
246817                          Ruj's Coffee                   Chiang Rai   
246818                               Coffman                    Khon Kaen   
246819                           ลากูนเทอเรซ                  Surat Thani   
246820                              Riliro's                     Ōsaka-fu   
246821                          ผู้ชายขายหอย  Bangkok Metropolitan Region   
246822                            Chang Xing  Bangkok Metropolitan Region   
246823                          Takumi-chaya                     Gifu-ken   
246824              โรงแรมทาวน์อินทาวน์พัทยา                    Chon Buri   
246825                           โค้งลาบเป็ด                Nakhon Phanom   
246826                             ลาบเขยยอง                   Chiang Mai   
246827                       สำราญโภชนา อตก.  Bangkok Metropolitan Region   
246828                               แพอลิสา                 Kanchanaburi   
246829                   Fatboy's Burger Bar               Kamphaeng Phet   
246830       ดิ อิมพีเรียล หัวหิน บีชรีสอร์ท                      Hua Hin   
246831                            ครัวศาลายา  Bangkok Metropolitan Region   
246832                             โชคดีกาแฟ                      เขาใหญ่   
246833                           เบอร์นีบาร์                  Surat Thani   
246834                             Kuppadeli  Bangkok Metropolitan Region   
246835                        ร้านครัวแกงป่า  Bangkok Metropolitan Region   
246836                                คนึงหา                  Phatthalung   
246837                         บึงกา

In [57]:
search_click_df.head()

click_timestamp                             search_id  business_id  \
0         11:38.9  5c004472-5ecc-4159-9698-9f329b8e26e1     298839.0   
1         30:51.3  5f34eca0-c04e-4c10-b600-54aa447dbd8e     171372.0   
2         32:09.6  8dc6d1f0-11f1-4239-9dd2-5c1674c81224      16157.0   
3         00:59.8  1a5810e9-3d1f-44b9-9a2e-26ede21c524b      89741.0   
4         23:36.8  6bc75e0d-fc65-471e-9926-ff6be6708639     189564.0   

   display_position  time_diff_nanos   ads  
0                 0     2.222400e+15  True  
1                 0     4.608380e+14  True  
2                 0     2.581490e+15  True  
3                 1     1.404580e+15  True  
4                 1     9.333590e+14  True

ทำการรวมตาราง 2 ตารางโดยต้องหา KEY ที่จะเชื่อมกันได้
โดยพบว่าตากตาราง small_table ไม่มี Key ที่จะสามารถเชื่อกับตาราง search_click_df.ได้
จึงต้อทำการเพิ่มคอลัมน์อีกในตาราง small_table และ w_restaurant_df

### combine two table

![combinetable](table.png)

## add column from another table

In [61]:
w_restaurant_df['id']

0              2
1              4
2              5
3              6
4              7
5             14
6             15
7             16
8             20
9             21
10            24
11            27
12            28
13            29
14            30
15            32
16            34
17            35
18            36
19            37
20            38
21            41
22            42
23            44
24            45
25            46
26            49
27            50
28            51
29            52
           ...  
246817    340007
246818    340011
246819    340015
246820    340022
246821    340024
246822    340025
246823    340027
246824    340028
246825    340029
246826    340031
246827    340035
246828    340036
246829    340037
246830    340038
246831    340041
246832    340042
246833    340043
246834    340048
246835    340051
246836    340054
246837    340056
246838    340059
246839    340060
246840    340063
246841    340067
246842    340068
246843    340070
246844    3400

In [59]:
small_table['id'] = w_restaurant_df['id']

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [60]:
small_table.head()

name                    city_name zipcode  \
0  นครินทร์ทันตกรรม              Samut Songkhram   75000   
1      Corner House  Bangkok Metropolitan Region   12150   
2    วัดโลกยสุธาราม     Phra Nakhon Si Ayutthaya   13000   
3    นันท์คาราโอเกะ  Bangkok Metropolitan Region   10700   
4       Buono Caffe  Bangkok Metropolitan Region   10220   

   weighted_average_rating  id  
0                 5.000000   2  
1                 2.000000   4  
2                 4.000000   5  
3                 0.000000   6  
4                 3.738462   7

### add business name to search_click
.map()

In [65]:
search_click_df.head()

click_timestamp                             search_id  business_id  \
0         11:38.9  5c004472-5ecc-4159-9698-9f329b8e26e1     298839.0   
1         30:51.3  5f34eca0-c04e-4c10-b600-54aa447dbd8e     171372.0   
2         32:09.6  8dc6d1f0-11f1-4239-9dd2-5c1674c81224      16157.0   
3         00:59.8  1a5810e9-3d1f-44b9-9a2e-26ede21c524b      89741.0   
4         23:36.8  6bc75e0d-fc65-471e-9926-ff6be6708639     189564.0   

   display_position  time_diff_nanos   ads  
0                 0     2.222400e+15  True  
1                 0     4.608380e+14  True  
2                 0     2.581490e+15  True  
3                 1     1.404580e+15  True  
4                 1     9.333590e+14  True

ชื่อตาราง[ชื่อคอลัมน์ใหม่] = ชื่อตารางหลักนี้ตามด้วย[keyตารางหลัก] ไป.mapกับ(อีกตารางหนึ่ง.setindex(keyของตารางรอง)[_])

In [67]:
search_click_df['business_name'] = search_click_df['business_id'].map(small_table.set_index('id')['name'])

In [68]:
search_click_df.head()

click_timestamp                             search_id  business_id  \
0         11:38.9  5c004472-5ecc-4159-9698-9f329b8e26e1     298839.0   
1         30:51.3  5f34eca0-c04e-4c10-b600-54aa447dbd8e     171372.0   
2         32:09.6  8dc6d1f0-11f1-4239-9dd2-5c1674c81224      16157.0   
3         00:59.8  1a5810e9-3d1f-44b9-9a2e-26ede21c524b      89741.0   
4         23:36.8  6bc75e0d-fc65-471e-9926-ff6be6708639     189564.0   

   display_position  time_diff_nanos   ads            business_name  
0                 0     2.222400e+15  True        ปูดองอันยอง Eight  
1                 0     4.608380e+14  True                Yoshinoya  
2                 0     2.581490e+15  True  The Hub Cafe and Eatery  
3                 1     1.404580e+15  True     ซั่งไห่ เสี่ยวหลงเปา  
4                 1     9.333590e+14  True                Yoshinoya

.merge()

## combine two table รวมกันทั้งตาราง
how ='left' บอกว่าตัวไหนคือตารางหลัก left_on ='business_id',right_on='id' บอกคีย์ของตารางที่ตรงกัน

In [70]:
merged_table = search_click_df.merge(small_table, how = 'left',left_on = 'business_id',right_on='id')

In [71]:
merged_table.head()

click_timestamp                             search_id  business_id  \
0         11:38.9  5c004472-5ecc-4159-9698-9f329b8e26e1     298839.0   
1         30:51.3  5f34eca0-c04e-4c10-b600-54aa447dbd8e     171372.0   
2         32:09.6  8dc6d1f0-11f1-4239-9dd2-5c1674c81224      16157.0   
3         00:59.8  1a5810e9-3d1f-44b9-9a2e-26ede21c524b      89741.0   
4         23:36.8  6bc75e0d-fc65-471e-9926-ff6be6708639     189564.0   

   display_position  time_diff_nanos   ads            business_name  \
0                 0     2.222400e+15  True        ปูดองอันยอง Eight   
1                 0     4.608380e+14  True                Yoshinoya   
2                 0     2.581490e+15  True  The Hub Cafe and Eatery   
3                 1     1.404580e+15  True     ซั่งไห่ เสี่ยวหลงเปา   
4                 1     9.333590e+14  True                Yoshinoya   

                      name                    city_name zipcode  \
0        ปูดองอันยอง Eight  Bangkok Metropolitan Region   10110   
1                Yoshinoya  Bangkok Metropolitan Region     NaN   
2  The Hub Cafe and Eatery  Bangkok Metropolitan Region     NaN   
3     ซั่งไห่ เสี่ยวหลงเปา  Bangkok Metropolitan Region   10900   
4                Yoshinoya  Bangkok Metropolitan Region   10110   

   weighted_average_rating        id  
0                 3.836735  298839.0  
1                 3.118367  171372.0  
2                 4.015184   16157.0  
3                 3.444134   89741.0  
4                 2.972672  189564.0

![joinpandas table](pandas-dataframe-shadow.png)

HW
ไปทำความเข้าใจและอธิบายตาราง Creating Pandas Dataframes

In [11]:
import pandas as pd

## Dictionary / Row Oriented

In [12]:
sales1 = [{'account':'Jones LLC','Jan':'150','Feb':'200','Mar':'140'},
              {'account':'Alpha Co','Jan':'200','Feb':'210','Mar':'215'},
              {'account':'Blue Inc','Jan':'50','Feb':'90','Mar':'95'}]
df1 = pd.DataFrame(sales1)
df1

Feb  Jan  Mar    account
0  200  150  140  Jones LLC
1  210  200  215   Alpha Co
2   90   50   95   Blue Inc

## List Row Oriented
### จากรูปที่โหลดมาผิดตรง List Row Oriented
มีการเรียงตัวเลขผิด โดยแก้ใหม่คือ สลับ 50 กับ 140 และ90กับ 215 จึงจะถูกต้อง

In [13]:
sales2 = [('Jones LLC','150','200','140'),
              ('Alpha Co','200','210','215'),
              ('Blue Inc','50','90','95')]
labels = ['account','Jan','Feb','Mar']
df2 = pd.DataFrame.from_records(sales2,columns = labels)
df2

account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95

## Dictionary Cotumn Oriented

In [14]:
sales3 = {'account': ['Jones LLC', 'Alpha co', 'Blue Inc'], 
             'Jan': [150, 200, 50], 
             'Feb': [200, 210, 90], 
             'Mar': [140, 215, 95]}
df3 = pd.DataFrame.from_dict(sales3)
df3

account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha co  200  210  215
2   Blue Inc   50   90   95

## List Contumn Oriented

In [15]:
sales4 = [('account', ['Jones LLC', 'Alpha co', 'Blue Inc']), 
            ('Jan', [150, 200, 50]), 
            ('Feb', [200, 210, 90]), 
            ('Mar', [140, 215, 95]) ]
df4 = pd. DataFrame.from_items (sales4)
df4

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  """


account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha co  200  210  215
2   Blue Inc   50   90   95